"""
run_weekly.py — Entrypoint. Reads one project plan file, runs the full
pipeline (ingest -> signals -> narrative), writes a Markdown + JSON weekly
report, and stores a snapshot so the NEXT real run can show genuine
week-over-week deltas. No history is fabricated: if no prior snapshot
exists, the report simply omits the trend section rather than inventing one.

Usage:
    python run_weekly.py /path/to/project_plan.xlsx
    python run_weekly.py /path/to/project_plan.xlsx --as-of 2026-07-10
"""

import argparse
import datetime
import json
import os
import re

from ingest import load_project
from signals import compute_all_signals
from narrative import generate_narrative
import investigate

STORAGE_DIR = os.path.join(os.path.dirname(__file__), "storage")
REPORTS_DIR = os.path.join(os.path.dirname(__file__), "reports")


def _slugify(name):
    return re.sub(r"[^a-z0-9]+", "_", (name or "project").lower()).strip("_")


def _snapshot_path(project_name):
    return os.path.join(STORAGE_DIR, f"{_slugify(project_name)}.json")


def _load_prior_snapshot(project_name):
    path = _snapshot_path(project_name)
    if not os.path.exists(path):
        return None
    with open(path) as f:
        return json.load(f)


def _save_snapshot(project_name, signals):
    os.makedirs(STORAGE_DIR, exist_ok=True)
    path = _snapshot_path(project_name)
    history = []
    if os.path.exists(path):
        with open(path) as f:
            existing = json.load(f)
            history = existing.get("history", [])
    history.append(signals)
    with open(path, "w") as f:
        json.dump({"project_name": project_name, "history": history}, f, indent=2, default=str)


def _investigate_contradictions(project, signals):
    """Scoped agentic enrichment for the Data Integrity Check ONLY. Runs after
    the color is already decided; attaches richer explanations without ever
    touching signals['data_integrity']['color'] or ['contradictions']. Bounded
    to the first 3 contradictions to cap cost."""
    contradictions = signals["data_integrity"]["contradictions"]
    if not contradictions:
        return
    signals["data_integrity"]["investigations"] = [
        investigate.investigate_contradiction(project, con)
        for con in contradictions[:3]
    ]


def _short_repr(value, limit=160):
    """Compact one-line repr of a tool result for the audit trail."""
    text = repr(value)
    text = " ".join(text.split())
    return text if len(text) <= limit else text[: limit - 1] + "…"


def _compute_trend(prior, current):
    if prior is None:
        return None
    prior_latest = prior["history"][-1]
    return {
        "prior_as_of": prior_latest["as_of"][:10],
        "overall_rag_change": f'{prior_latest["overall_rag"]} -> {current["overall_rag"]}',
        "pct_overdue_change": round(
            current["schedule"]["pct_overdue"] - prior_latest["schedule"]["pct_overdue"], 1
        ),
        "overdue_count_change": (
            current["schedule"]["overdue_count"] - prior_latest["schedule"]["overdue_count"]
        ),
        "milestone_pct_change": round(
            current["milestone"]["pct_overdue"] - prior_latest["milestone"]["pct_overdue"], 1
        ),
    }


def _render_markdown(signals, narrative, trend):
    lines = []
    lines.append(f"# Weekly Project Health Report — {signals['project_name']}")
    lines.append(f"*As of {signals['as_of'][:10]}*")
    lines.append("")
    lines.append(f"## Overall status: **{signals['overall_rag']}**")
    lines.append("")
    lines.append(narrative["text"])
    lines.append("")
    lines.append(f"*(Narrative generated by: {narrative['generated_by']}"
                  + (f" — fallback reason: {narrative['fallback_reason']}" if narrative.get("fallback_reason") else "")
                  + ")*")
    lines.append("")

    if trend:
        lines.append("## Change since last run")
        lines.append(f"- Prior run: {trend['prior_as_of']}")
        lines.append(f"- Overall RAG: {trend['overall_rag_change']}")
        lines.append(f"- % active tasks overdue: {trend['pct_overdue_change']:+.1f} pts")
        lines.append(f"- Overdue task count: {trend['overdue_count_change']:+d}")
        lines.append(f"- Milestone overdue %: {trend['milestone_pct_change']:+.1f} pts")
        lines.append("")
    else:
        lines.append("## Change since last run")
        lines.append("*No prior snapshot found — this is the first recorded run for this project. "
                      "Trend data will appear starting with the next run.*")
        lines.append("")

    lines.append("## Signal detail")
    lines.append("")
    lines.append(f"| Signal | Status | Detail |")
    lines.append(f"|---|---|---|")
    s = signals["schedule"]
    lines.append(f"| Schedule Slippage | {s['color']} | {s['overdue_count']}/{s['active_count']} active tasks overdue ({s['pct_overdue']}%) |")
    c = signals["critical_path"]
    lines.append(f"| Critical-Path Override | {c['color']} | {c['overdue_critical_count']} overdue task(s) on critical path |")
    m = signals["milestone"]
    lines.append(f"| Milestone Health | {m['color']} | {m['pct_overdue']}% of {m['total_phases']} major phases overdue |")
    di = signals["data_integrity"]
    lines.append(f"| Data Integrity Check | {di['color']} | {len(di['contradictions'])} status/comment contradiction(s) found |")
    b = signals["blockers_sentiment"]
    sentiment_detail = "no comment data available" if not b["comment_data_available"] else f"{len(b['flagged_comments'])} risk-flagged comment(s)"
    lines.append(f"| Blockers & Sentiment (lagging) | — | {sentiment_detail} |")
    lines.append("")

    if signals["data_integrity"]["contradictions"]:
        contradictions = signals["data_integrity"]["contradictions"]
        lines.append("## Data integrity contradictions (detail)")
        for con in contradictions:
            lines.append(f"- **{con['task_name']}** — status `{con['status']}`, but comment reads: \"{con['comment']}\"")
        lines.append("")

        # Investigation trace: only rendered when an actual (non-fallback)
        # agentic investigation ran. When every contradiction fell back (e.g.
        # no API key), this section is omitted entirely — the color and the
        # contradictions above are unchanged either way.
        investigations = signals["data_integrity"].get("investigations") or []
        traced = [
            (con, inv)
            for con, inv in zip(contradictions, investigations)
            if inv.get("generated_by") != "fallback-no-investigation"
        ]
        if traced:
            lines.append("### Investigation trace")
            lines.append("*Agentic enrichment of the contradictions above — the Data Integrity "
                          "color is unchanged; this only adds explanation and shows the "
                          "reasoning steps taken.*")
            lines.append("")
            for con, inv in traced:
                lines.append(f"- **{con['task_name']}** — {inv['enriched_finding']}")
                lines.append(f"  - _generated by: {inv['generated_by']}_")
                if inv.get("tool_calls"):
                    lines.append("  - Tool calls made:")
                    for tc in inv["tool_calls"]:
                        args_str = ", ".join(f"{k}={v!r}" for k, v in (tc.get("args") or {}).items())
                        lines.append(f"    - `{tc['tool']}({args_str})` → {_short_repr(tc['result'])}")
                else:
                    lines.append("  - _(no tool calls recorded)_")
            lines.append("")

    if signals["source_conflicts"]:
        lines.append("## Conflicts with source file's own fields")
        for conflict in signals["source_conflicts"]:
            lines.append(f"- {conflict}")
        lines.append("")

    return "\n".join(lines)


def run(file_path, as_of=None):
    today = as_of or datetime.datetime.now()
    project = load_project(file_path)
    prior = _load_prior_snapshot(project["project_name"])
    signals = compute_all_signals(project, today=today)
    # Scoped agentic step: enrich data-integrity contradictions only. This must
    # run after the color is decided and before the narrative; it never changes
    # the RAG color.
    _investigate_contradictions(project, signals)
    trend = _compute_trend(prior, signals)
    narrative = generate_narrative(signals)
    markdown = _render_markdown(signals, narrative, trend)

    os.makedirs(REPORTS_DIR, exist_ok=True)
    slug = _slugify(project["project_name"])
    date_tag = today.strftime("%Y%m%d")
    md_path = os.path.join(REPORTS_DIR, f"{slug}_{date_tag}.md")
    json_path = os.path.join(REPORTS_DIR, f"{slug}_{date_tag}.json")

    with open(md_path, "w", encoding="utf-8") as f:
        f.write(markdown)
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump({"signals": signals, "narrative": narrative, "trend": trend}, f, indent=2, default=str)

    _save_snapshot(project["project_name"], signals)

    return {"markdown_path": md_path, "json_path": json_path, "signals": signals}


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("file_path")
    parser.add_argument("--as-of", default=None, help="Override 'today' as YYYY-MM-DD (for testing/backfill)")
    args = parser.parse_args()

    as_of = datetime.datetime.strptime(args.as_of, "%Y-%m-%d") if args.as_of else None
    result = run(args.file_path, as_of=as_of)
    print(f"Overall RAG: {result['signals']['overall_rag']}")
    print(f"Report written to: {result['markdown_path']}")
